### ISSUE TITLE
Warning: Failed child context type: Invalid child context `virtualizedCell.cellKey` of type `number` supplied to `CellRenderer`, expected `string`.

### ISSUE THREAD

**Issue by frantz101** [joshjhargreaves/react-native-event-calendar#15]
Anyone Know why i am getting this warning?
Here is my Package JSON 
{
  "name": "myApp",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "react-native-scripts": "1.14.0",
    "jest-expo": "~27.0.0",
    "react-test-renderer": "16.3.1"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "jest"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "expo": "^27.0.1",
    "react": "16.3.1",
    "react-native": "~0.55.2",
    "react-native-events-calendar": "^1.0.8",
    "react-native-material-cards": "^1.0.9",
    "react-native-material-ui": "^1.30.1",
    "react-native-vector-icons": "^5.0.0",
    "react-navigation": "^2.9.3"
  }
}
and here is the code snippet
import React from 'react';
import { StyleSheet, View , Text, SafeAreaView, Dimensions, ListView} from 'react-native';
import BottomNavigation from './utils/bottomNav'
import title from './utils/setTitle'
import EventCalendar from 'react-native-events-calendar'

const events = [
  { start: '2017-09-07 00:30:00', end: '2017-09-07 01:30:00', title: 'Dr. Mariana Joseph', summary: '3412 Piedmont Rd NE, GA 3032' },
  { start: '2017-09-07 01:30:00', end: '2017-09-07 02:20:00', title: 'Dr. Mariana Joseph', summary: '3412 Piedmont Rd NE, GA 3032' },
  { start: '2017-09-07 04:10:00', end: '2017-09-07 04:40:00', title: 'Dr. Mariana Joseph', summary: '3412 Piedmont Rd NE, GA 3032' },
  { start: '2017-09-07 01:05:00', end: '2017-09-07 01:45:00', title: 'Dr. Mariana Joseph', summary: '3412 Piedmont Rd NE, GA 3032' },
  { start: '2017-09-07 14:30:00', end: '2017-09-07 16:30:00', title: 'Dr. Mariana Joseph', summary: '3412 Piedmont Rd NE, GA 3032' },
  { start: '2017-09-08 01:20:00', end: '2017-09-08 02:20:00', title: 'Dr. Mariana Joseph', summary: '3412 Piedmont Rd NE, GA 3032' },
  { start: '2017-09-08 04:10:00', end: '2017-09-08 04:40:00', title: 'Dr. Mariana Joseph', summary: '3412 Piedmont Rd NE, GA 3032' },
  { start: '2017-09-08 00:45:00', end: '2017-09-08 01:45:00', title: 'Dr. Mariana Joseph', summary: '3412 Piedmont Rd NE, GA 3032' },
  { start: '2017-09-08 11:30:00', end: '2017-09-08 12:30:00', title: 'Dr. Mariana Joseph', summary: '3412 Piedmont Rd NE, GA 3032' },
  { start: '2017-09-09 01:30:00', end: '2017-09-09 02:00:00', title: 'Dr. Mariana Joseph', summary: '3412 Piedmont Rd NE, GA 3032' },
  { start: '2017-09-09 03:10:00', end: '2017-09-09 03:40:00', title: 'Dr. Mariana Joseph', summary: '3412 Piedmont Rd NE, GA 3032' },
  { start: '2017-09-09 00:10:00', end: '2017-09-09 01:45:00', title: 'Dr. Mariana Joseph', summary: '3412 Piedmont Rd NE, GA 3032' }
]

class HomeScreen extends React.Component {
  constructor(props){
    super(props)
    const ds = new ListView.DataSource({rowHasChanged: (r1, r2) => r1 !== r2});
    this.state = {
      events: ds.cloneWithRows(events)._dataBlob.s1,
    }
  }
  
  static navigationOptions =  title('Agenda')

  
  render() {
    console.log(this.state.events);
    const width= Dimensions.get('window')
    return (
        <View  style={styles.container}>
        <SafeAreaView style={styles.safeArea}>
          <EventCalendar
            events={this.state.events}
            width={width.width}
            initDate={'2017-09-08'}
        />
        </SafeAreaView>
        <BottomNavigation active={{active: this.props.navigation.getParam('active', 'agenda')}} navigate={this.props.navigation.navigate} />
     </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  safeArea: {
    flex: 5,
  }
});
export default HomeScreen;

**Comment by jackfan108** [comment]
`keyExtractor` takes a function that returns a string, not a number. This is fixed in 
[this PR here](https://github.com/joshjhargreaves/react-native-event-calendar/pull/10/files#diff-eca1225a5b5547e5ede5beb7b1f88606R150). The source code on github is updated but seems like it's not updated on npm yet. @joshjhargreaves any plans on updating on npm?

**Comment by joshjhargreaves** [comment]
@jackfan108 I will do an npm release soon: in the meantime you could use the package as a git dependency: 
```
react-native-event-calendar: "git+https://github.com/joshjhargreaves/react-native-event-calendar#4b56322df6c70ea3068153dab47227fad2e2c183"
```

**Comment by joshjhargreaves** [comment]
Will be fixed by a new release to npm: https://github.com/joshjhargreaves/react-native-event-calendar/issues/17

**Comment by AgingChan** [comment]
NPM is not updated yet?

**Comment by jeanDenison** [comment]
Hi am still having this annoying warning;

**Comment by jsnavarroc** [comment]
2020 And they still don't update it, please update it!!!
